### ISSUE TITLE
Getting rid of PyPSA fork

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#101]
The dependency links to a forked repository are suboptimal. Therefore it should be checked if we can PR our changes into the mother repository and be able to use the original PyPSA.
The changes in our [dev](https://github.com/openego/PyPSA/tree/dev) and our [snapshot clustering branch](https://github.com/openego/PyPSA/tree/features/snapshot_clustering) have to be considered.

The change in the snapshot clustering branch will definitely not go into the mother repository because it displays a hard-coded individual solution. @kimvk can you check if the adjustment could be done outside of PyPSA within eTraGo?

Concerning the ehv network clustering which display the changes in the dev branch, @s3pp would you think they would be accepted by the pypsa developer or are they too specific and fit only to our problem? Should I just try a PR and if it is rejected we can try to find a solution outside of PyPSA?!

**Comment by ulfmueller** [comment]
or do you disagree @BartelsJ @wolfbunke @lukasoldi ? should we just keep the fork and not bother about this stuff?
The advantage would be that concerning eGo eTraGo and eDisGo would be integrated a bit more straight foreword. Moreover we would have less problems with installation and documentation - since these fork dependencies are rather not wanted and therefore can cause problems....

**Comment by lukasoldi** [comment]
I would definitely welcome an integration into the main version and make it more straightforward. But, I think we should see what @s3pp says about the issues concerning networkclustering. 
Generally, you should consider the workload for the re-integration. I remember that we decided for the fork also with the argument that we can do our own stuff independently...

**Comment by wolfbunke** [comment]
I am fine with a switch to the original PyPSA. But I am not sure about the workload of the re-integration as well.

**Comment by s3pp** [comment]
![20171123_pypsaforkdiff](https://user-images.githubusercontent.com/10025949/33183776-87b1f2fa-d079-11e7-91f6-098f85553dce.png)

There are only a few changes between dev and master branch, but even so I'm sure, that these changes cannot be merged back in the official PyPSA repository, because grouping on max_hours if available in aggregateoneport is a very specific change. Nevertheless, due to the fact that by now only these two functions are concerned, reimplementing those in eTraGo should not be very time-consuming.

**Comment by ClaraBuettner** [comment]
PyPSA 0.17.1 allows to get rid of the fork within the next release (0.8.0). All changes of the pypsa-fork are implemented in the newer version or can be moved to etrago: 

- strategies of aggregategenerators can be adjusted by custom_strategies in etrago/cluster/networkclustering.py
https://github.com/openego/eTraGo/blob/00847d3acba5e7bb99e061dea414c5ca962effd7/etrago/cluster/networkclustering.py#L592-L596

- storage_units can not be grouped by their max_hours attribute, but by the carrier, so changing the carrier to 'extendable_batterry_storage' and 'extendable_hydrogen_storage' can solve the problem 
https://github.com/openego/eTraGo/blob/00847d3acba5e7bb99e061dea414c5ca962effd7/etrago/network.py#L139-L147

- snapshot_weightings and line expansion costs are set correctly in network clustering in newer pypsa-versions

- k means busmap can be saved and loaded in etrago instead of im-/exporting the bus_weighting in pypsa:
https://github.com/openego/eTraGo/blob/c5426ded74b1f696bc6fd0a33cd7398ead72c518/etrago/cluster/networkclustering.py#L568-L583

- s_nom_total can be replaced by using s_max_pu for n-1-security factor

**Comment by ClaraBuettner** [comment]
The branch is already merged into dev so I close this issue.
