### ISSUE TITLE
Test, validate and merge snapshot clustering

### ISSUE THREAD

**Issue by lukasol** [openego/eTraGo#13]
Similarly to network clustering, I also suggest to merge snapshot clustering into dev...

**Comment by lukasol** [comment]
- [ ] insert latest dev changes into snapshot clustering branch @ulfmueller 
- [ ] try merging updated snapshot clustering into dev

**Comment by ulfmueller** [comment]
I adjusted the snapshot clustering with respect to the above check. @simnh you could now try out if it works. Better not do it before tomorrow because the oedb moves to a new server today...

**Comment by lukasol** [comment]
Is there a new status here?

**Comment by ulfmueller** [comment]
I just pulled the recent dev into the snapshot feature branch and I tried to get it running. I just pushed a very dirty solution which seems to work. @simnh you can have a look at it (last very dirty commit: df6d92ad2bfde7fce037f3905e19952ec04b00ab) Since it did not work out today, when shall we meet in order to move on? do you have any time this week? I think if we meet, after that I would be able to perform the desired optimization runs without you...

**Comment by lukasol** [comment]
I assume this has not been finished for Release 0.4 and remove the milestone.

**Comment by ulfmueller** [comment]
@kimvk I assume I can delete this [branch](https://github.com/openego/eTraGo/tree/features/snapshot_clustering_goes_app) because you created a new one?

**Comment by ulfmueller** [comment]
@kimvk The structure of your integration looks quite final. Does it work already?
One remark: I would shift the functions from [snapshot_cl.py](https://github.com/openego/eTraGo/blob/features/snapshot_clustering_app/etrago/cluster/snapshot_cl.py) to the ['original' file](https://github.com/openego/eTraGo/blob/features/snapshot_clustering_app/etrago/cluster/snapshot.py)

**Comment by kimvk** [comment]
Yes you can delete the Branch Features/snapshot_clustering_goes_app. I will shift the functions in the Original file, thought about that too. 
The plots and to store the results as csv does not work very well. It is hard to evaluate the results.
