### ISSUE TITLE
Some generators have 2*8760 values for p_max_pu & p_set

### ISSUE THREAD

**Issue by jankaeh** [openego/eTraGo#130]
I already pointed this out at the oeplatform repository (https://github.com/openego/oeplatform/issues/306), but now I believe the issue is better placed here, as the table seems to be an output of eTraGo:

There seem to be six generators in the table ego_pf_hv_generator_pq_set in the grid schema of the database with twice as many values for p_max_pu and for p_set as normal:
https://oep.iks.cs.ovgu.de/dataedit/view/grid/ego_pf_hv_generator_pq_set
(version=v0.3.0, scn_name=Status Quo)
generator_id:
'200047', '200048', '200056', '200057', '200062', '200063'

Is this a bug, or is the interval 30 min instead of one hour?

**Comment by ulfmueller** [comment]
Thanks for mentioning this curiosity! It is definitely not a 30min interval. Just by looking on the generator_id those buses should be buses of neighboring countries. To me it seems to be a bug.
Actually theses values are input values of eTraGo. So the best place for this issue is the ['data processing'](https://github.com/openego/data_processing) @IlkaCu Could you handle this and/or move it to the issues in the data processing repository?

**Comment by IlkaCu** [comment]
I created an issue in the DP repository concerning this bug and I'll take care of it as soon as possible.
