### ISSUE TITLE
Find best solver_options

### ISSUE THREAD

**Issue by maltesc** [openego/eTraGo#159]
Since I have some trouble finding the correct solver options, I opened this issue in order to discuss the different options.
First, I have tried these settings: https://github.com/openego/eTraGo/blob/features/storage-paper/etrago/appl.py#L295, However, I get the error message: `ValueError: Cannot load a SolverResults object with bad status: error`. @ClaraBuettner, I remember you had the same problem. Have you solved it?

I have checked the parameters in the gurobi docu (http://www.gurobi.com/documentation/8.0/refman/parameters.html), but this is not really helping at first sight. 

The option `solver_options={'threads':4}` works fine for me. As far as I can see in htop, gurobi uses the indicated 4 cores then. However, @ulfmueller  said the other options should increase the performance even better.

I don't know if this is of any interest, but I am using a modified version of `eTraGo 0.5.1.`

**Comment by MarlonSchlemminger** [comment]
I have never looked into the solveroptions so far, so I don't think I can contribute to this issue. What I have experimented with a little bit is the formulations (angles and kirchhoff) and generally, angles is faster in small networks and kirchhoff is faster in bigger networks. I don't know the break even point though.

**Comment by ClaraBuettner** [comment]
Yes I had problems with the solver options as well. It seemed to be random if the calculation works on the server, but I couldn't find the reason why. With my laptop it never worked. With smaller problems the possibility to run is higher, so I guess it has something to do with the RAM which is much smaller in my laptop. Did you tried to calculate on the server or locally?
I also tried to understand the settings, and tested if other ones work. I think the setting 'crossover' cause the problem, but without this the much faster method 2 only uses one thread and is much slower.

**Comment by BartelsJ** [comment]
Do you have also check the log-file to proof whether the barrier method is better at solving your problem than dual simplex for example? Sometimes I had some comments in the file that barrier was non-optimal. Regarding a speed-up of the simulation I would also suggest the kirchhoff formulation for LOPF calculations as mentioned by @MarlonSchlemminger and increase the convergence tolerances carefully. But the effects are not investigated yet as far as I know.

**Comment by ClaraBuettner** [comment]
I don't know how useful this is currently, but I guess I found a possible reason for the problems with the solver options. The setting Crossover : 0 seems to be a problem, the setting disables crossover (which transforms the interior solution into a basic solution) (http://www.gurobi.com/documentation/7.5/refman/crossover.html). That's faster because of the missing transformation, but the interior solution needs much more RAM then the basic one. That's way the setting works more often for smaller problems and more often on the server than local. 
When setting Crossover to 1 (or any other possibility), it works always. But than the solver sometimes only uses less treads and will be slower. I can try to find the reason for this and find the best crossover-setting.

**Comment by ClaraBuettner** [comment]
SolverOptions are documented in #213, so I'll close this issue.
