### ISSUE TITLE
Order of k_means clustering and scn_extension

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eTraGo#183]
When using k_mean-clustering and an extension-scenario the order of these functions is important. 
If k_means is applied first, only the existing scenario is clustered and the new buses and lines are added to this clustered network without any changes. 
The other way around, the components of the extension scenario are included in the clustering. This way, the extension-lines and buses get somehow lost in the clustering and it's not possible to differentiate them from the components of the existing network. 
Up to now, scn_extension was used to calculate with new lines in respect to the NEP. To rate the effect of these lines, it was necessary to leave them unchanged. That's why k_means comes first currently. 
But with other scn_extension the other way might be better.

**Comment by ulfmueller** [comment]
This relates to a problem we encountered with the [disaggregation method](https://github.com/openego/eTraGo/tree/features/disagg-uniform). Since we change the clustered network after the clustering we get an inconsistency. This can (depending on the functionality does not has to) lead to a malfunctioning of the disagg-uniform method. In the mentioned branch I changed the order therefore. 

To picture to exemplary opposing use cases: 
a) someone wants to do the above mentioned by @ClaraBuettner . cluster a network and the evaluate a particular power line or additional generator - thus this one would be added afterwards. -> implies the actual ordering of the dev
b) someone needs results on the entire grid in its original complexity and wants to activate the desagg-uniform. -> implies a different ordering such as the one in the feature/disagg-uniform branch

I am not sure what is best but definitely once using the desagg-uniform method there has to be a change. A more modular/flexible structure would be nice...

@gnn Any suggestions? Would it be possible that once the desagg-uniform is applied the logical ordering is changed? Or the other way around once the extension functions are applied and the desagg-uniform is not the ordering changes?

**Comment by ClaraBuettner** [comment]
This affects as well the calculation of capital costs in k means clustering. Currently, costs per v_nom are set after clustering, so all lines get costs for 380kV lines and will be underestimated. 
To implement a weighted average of costs for each line, costs need to be set before.

**Comment by ClaraBuettner** [comment]
This has been done in https://github.com/openego/eTraGo/pull/209 and https://github.com/openego/PyPSA/pull/7. Since the NEP-extendable scenarios are still visible when k mean clustering is applied last, this order was chosen.
