### ISSUE TITLE
disaggregation object does not want to be a pickle?!

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#215]
Using eGo's MV grid parallisation, the error occurs: TypeError("can't pickle memoryview objects",) which seems to happen due to the disaggregation method.

**Comment by maltesc** [comment]
I can't tell the reason for the former pickle-related error. However, I managed to run the parallelization with a subset of the eTraGo network, only containing the necessary information for eDisGo (see: https://github.com/openego/eGo/blob/49d3a8f2e9a0da28cf45a4875072ae7e7ca18180/ego/tools/edisgo_integration.py#L782-L800 and https://github.com/openego/eGo/blob/49d3a8f2e9a0da28cf45a4875072ae7e7ca18180/ego/tools/edisgo_integration.py#L130-L131).

Perhaps we should consider to implement this reduction already at (or right after) the desaggregation in order to reduce memory usage...

**Comment by ulfmueller** [comment]
I'd say this issue can be closed. Do you agree?
