### ISSUE TITLE
skip_snapshot is depreciated due to k_means_clustering()

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#217]
Since the order changed and the skip_snapshots is executed before the k_means_clustering the weighting after the clustering is 1 again. 
I do not get why. Changing the order fixes it but then disaggregation would have problems.
Any ideas?

**Comment by BartelsJ** [comment]
So the weighting of the snapshots is set to 1 again instead of the number of skipped snapshots? And the disaggregation works from the view of the clustering and does not regard aggregated snapshots additionally? 
Does the changes in disaggregation come along with a huge amount of work? If not, I prefer to change the order of reduction methods and adapt the disaggregation procedure.

**Comment by ulfmueller** [comment]
4c95eeac7c121dcb0dbdf14a34f11d1a99efb701 fixes it 'quick and dirty'. I would like to understand why this happens.... @gnn any ideas?

**Comment by ClaraBuettner** [comment]
This was solved in this Pypsa [PR](https://github.com/openego/PyPSA/pull/9).
