### ISSUE TITLE
Calculate grid loss costs with PF

### ISSUE THREAD

**Issue by lukasol** [openego/eTraGo#23]
See #10 for the implementation of the PF. 
Especially with regards to the eGo tool, we need full costs for grid losses.

- [x] Calculate the grid losses for all lines using the results of the PF
- [x] assume average costs to cover these losses

**Comment by lukasol** [comment]
Consider fundamentals of electricity...not just the simple diffs because with pf Q parts lead to increased flows.

**Comment by lukasol** [comment]
We'll mainly focus on the copper losses `P = I^2 x R` for all lines, calculated with the PF results.

Additionally, voltage-based losses for the transformers could be assumed by using the standard losses given by the producers for a specific set of pre-defined transformers. These are not dependent of the current and can thus easily be defined.

Other losses will be disregarded.

**Comment by ulfmueller** [comment]
as a base you can use the [pf_after_lopf branch](https://github.com/openego/eTraGo/tree/features/pf_after_lopf) for your loss calculation. It works very fine for the SH status quo scenario and for the timesteps chosen. But it seems to work fine with basically all snapshots. The problem is the bug in the x of the transformer which changes a lot. In the new dp version the x will be fine. In order to fix this bug temporally there is a line which downgrades the x of the tranformers at least in the order of magnitude where it should be (still being conservative). 
Anyhow, bottom line it generates pf results which you can use for loss calculation!

**Comment by lukasol** [comment]
I added the function `calc_line_losses` in https://github.com/openego/eTraGo/commit/eb4830805027b5ea62ec28a5a52096896a066ac4

@ulfmueller please check!

**Comment by ulfmueller** [comment]
Looks good. Havent tried it out yet. 
Which could be added is the calculation of the transformer copper losses. The copper losses of transformers can be calculated by
loss_tranformer = (apparent power S/S_nom)² * nominal copper losses of the transformer. There as well we have to make assumptions for our nominal copper losses...

**Comment by lukasol** [comment]
> loss_tranformer = (apparent power S/S_nom)² * nominal copper losses of the transformer. There as well we have to make assumptions for our nominal copper losses...

That would mean that we do consider power-dependent losses of transformers. We could also just use the no-load losses according to the producers. Would you know of a nice source for this?

**Comment by lukasol** [comment]
The general logic has been implemented in #41 

Open issues:

- [ ] calculate copper losses for transformers
- [ ] find a nice way to include the results of the loss calculations to the network container

**Comment by lukasol** [comment]
https://github.com/openego/eTraGo/commit/c2ba428ffd08367c30fec3335852607e195a2816 solved the remaining issues. Transformer losses are now calculated with a simple assumption of efficiency according to literature.
