### ISSUE TITLE
BE_NO_NEP 2035 is missing two storage units

### ISSUE THREAD

**Issue by OriolRaventos** [openego/eTraGo#288]
I tried to get the scenario v0.4.5, NEP2035 with extension BE_NO_NEP 2035 and it did not work. I also had to add the extension nep2035_b2. But anyway I still got the follwoing error:

> No data for StoragePqSet in column p_set.
> Series p_set of component StorageUnit could not be imported
> No data for GeneratorPqSet in column p_set.
> Series p_set of component Generator could not be imported
> No data for GeneratorPqSet in column p_max_pu.
> Series p_max_pu of component Generator could not be imported
> No data for LoadPqSet in column p_set.
> Series p_set of component Load could not be imported
> No data for LoadPqSet in column q_set.
> Series q_set of component Load could not be imported
> No data for StoragePqSet in column p_set.
> Series p_set of component StorageUnit could not be imported
> ERROR:pypsa.io:Error, new components for Carrier are not unique
> No data for StoragePqSet in column p_set.
> Series p_set of component StorageUnit could not be imported
> ERROR:pypsa.io:Error, new components for Carrier are not unique

This is because there are 2 storage units missing. That I found comparing with the data in OEP ‘ego_grid_pf_hv_extension_storage’. Everything can be corrected manually but there are a couple of other issues:

- The bus in BE is assigned to FR
- The bus in NO is assigned to SE
- What was supposed to be an wind offshore generator gets turned into a nuclear plant
- There is a run-of-river generator with p_max_pu much bigger than 1
- Two storage units are missing

**Comment by ClaraBuettner** [comment]
There is a new grid version v0.4.6 which fixes the last three errors. It is mainly a copy of v0.4.5 but involves a few changes in the extension and decommissioning scenarios and very small changes of installed capacities in NEP 2035 scenario. It is not compatible to eGo/eDisGo, but works fine if you only use eTraGo. 
The mismatch of Belgium and Norway doesn't affect the optimization. Those 'new' countries are currently not included in the 'buses_by_country'-function in etrago/utilities. When geopandas is installed, buses are assigned by shapefiles and Belgium and Norway are assigned correctly. 
"ERROR:pypsa.io:Error, new components for Carrier are not unique" is caused by duplicate Carrier values. But they are the same (at least in version v0.4.6) in NEP 2035 and the extension scenarios, so it's not affecting the optimization. Unfortunately, I didn't find a way to avoid this error-message when I implemented the extension-function.

**Comment by OriolRaventos** [comment]
Perfect. Thank you. I should be using v0.4.6. Everything clear. I'll close the issue then.
