### ISSUE TITLE
Test random noise to prevent optima plateau

### ISSUE THREAD

**Issue by lukasol** [openego/eTraGo#4]

**Comment by lukasol** [comment]
A one-liner to add random noise to all generators with marginal_cost of 0 has been added in https://github.com/openego/eTraGo/commit/4d970384074918783965cdf8382d1e87c733094f

Needs testing if this is able to prevent optima plateaus.

**Comment by lukasol** [comment]
Since the random noise is generated really randomly each time, it might make sense to do this manipulation closer to the database in order to allow comparison of results with the same noise.

**Comment by ulfmueller** [comment]
@wolfbunke thinking about the RE allocation within the grid district, this 'random but reproducible paradoxon' was also something which was discussed. Is there anything you learned which we can use in this context?
Generally it would be interesting if this sth. the Frankfurter have thought about and if yes how the dealt with it...

**Comment by wolfbunke** [comment]
As fare as I know the random allocation is predefined by by its types and size. By using a small spacial grid  the new position can only be used ones. The difference are tagged by geom, new_geom, and an distance line geom.  By having the unique unit id and the new and old geom the difference are comparable. 

In your case I would use a log table with the an unique and assignable ID and the value in order to compare the random values. By having various samples of one id with different values you can use a statistic analyse in order to find and set a e.g a mean or similar standard value.    

I hope I have understood the question right and could help.

**Comment by lukasol** [comment]
the random noise can be reproduced with `np.random.seed()` which is already part of the top part of appl.py

Reproduction for different scenarios is not possible.

**Comment by ulfmueller** [comment]
another thing I just learned. This optima plateau is also called 'degeneracy'. [Here](https://ocw.mit.edu/courses/sloan-school-of-management/15-053-optimization-methods-in-management-science-spring-2013/tutorials/MIT15_053S13_tut07.pdf)  is a nice Tutorial explaining it....

**Comment by lukasol** [comment]
Test the dimension of the random noise!

**Comment by lukasol** [comment]
- read random noise from file or database result table. May be implemented in #29 
- discuss if noise can be repeated across scenarios in order to enable comparison
- if possible replace random noise utilization by #8

**Comment by lukasol** [comment]
The random noise can now be generated in the first run with a scenario / dataset. The noise is automatically saved to a .csv file and can be re-used in future runs with the same scenario / dataset. 
**Please note that manually disabling the creation of the .csv is necessary for that.** 

This works for now, but it would still be more elegant to achieve a similar result by #8.
