### ISSUE TITLE
Avoid numerical issues in LOPF

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eTraGo#405]
I also had some warnings regarding numerical issues, even if an optimal solution was found. I had a look into the lp file and found some possible reasons: 

- Some p_max_pu values of renewable generators are very small (e-28) and cause large bounds. I would suggest to find a maximum reasonable value and set all smaller values to 0. 
- Large capital costs of H2_to_power and power_to_H2 (e13) cause large objective coefficients. I don't know if that's is the expected magnitude. @fwitte Does that make sense to you?

**Comment by fwitte** [comment]
I ran the clustering on DE, it seems the capital_cost information gets distorted in the AC clustering. I made exports of the network before and after gas clustering:

[links_not_clustered.csv](https://github.com/openego/eTraGo/files/8377995/links_not_clustered.csv)

In gas clustering, with the strategy `"mean"` (I updated it locally only) for all link capital cost, I do get the follwing results, which seem somewhat consistent with the input values from the network *after* AC `k-means clustering` *without* `ehv clustering`.

[links_clustered.csv](https://github.com/openego/eTraGo/files/8377999/links_clustered.csv)

**Comment by ulfmueller** [comment]
@fwitte I have troubles to understand some parts of your findings. When you say you used the stragegy 'mean' locally, does that mean you added a line for the links' capital costs [here](https://github.com/openego/eTraGo/blob/dev/etrago/cluster/gasclustering.py#L530)?

**Comment by fwitte** [comment]
Yes, that is what I added, because I was not sure what the default strategy would be.

Independent of that, the capital cost information are already skewed after k-means clustering of AC. Unfortunately, I was not yet able to find, what is happening there.

**Comment by fwitte** [comment]
The function

https://github.com/openego/eTraGo/blob/23085ae4c5366a0619825fb0a1aba3cbfdcc4538/etrago/tools/utilities.py#L1113-L1115

called by

https://github.com/openego/eTraGo/blob/23085ae4c5366a0619825fb0a1aba3cbfdcc4538/etrago/appl.py#L404

with these settings

https://github.com/openego/eTraGo/blob/23085ae4c5366a0619825fb0a1aba3cbfdcc4538/etrago/appl.py#L59-L60

does the trouble.

**Comment by fwitte** [comment]
Update to my previous comment:

There is one more thing I am unsure about: In the db, `capital_cost` are identical within all links of the respective carrier `power_to_H2` (24049...), `H2_to_power` (132742...), `H2_to_CH4` (16392...) and `CH4_to_H2` (38354...).

After adjusting the network, the values are scaled as pointed out in above comment, therefore all values within each carrier are again identical.

After the AC k-means clustering, the `capital_cost` for the carriers `power_to_H2` and `H2_to_power` seem to be unique values for every link. This does not seem to be correct, since the value for all respective links are identical in the db (and after `adjust_network`).

For the instances of `H2_to_CH4` and `CH4_to_H2` links, the capital cost retain their correct value after gas k-means clustering.

**Comment by CarlosEpia** [comment]
Hi Francesco, thanks for pointing this out. The capital costs for links were weighted before the mean was calculated. It was already solved in 9467f15c40149910386151d2d96622f1e49278d0.

**Comment by fwitte** [comment]
Thank you for finding the fix so quick. Just one question: Isn't the weighting done for some reason? Or is it possible to just remove it? Maybe we can finalize it in the AP2 meeting today :)
