### ISSUE TITLE
corresponding release ego.io and ego.powerflow

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#42]
Due to this bda27bc99ab59d22e67bfe76d94043797e1c49d4 changes in ego.io and ego.powerflow are relevant. 
I would suggest we have small new releases in ego.io and ego.pf in order to hint to them in the setup.py. Otherwise we would have to link to the dev branches of those repos.

@lukasol aka release-master What do you think?

**Comment by lukasol** [comment]
Yes let's do this. 
@ulfmueller we can talk about the how-to in our scheduled call later. If that's too late, you could create PRs for the releases so that the other developers touched by that have a chance for feedback.

**Comment by lukasol** [comment]
I created the PR for ego.powerflow. 
For ego.io I don't know which branch to choose. The dev branch seems to be almost up to date with master...

**Comment by mariusves** [comment]
I've now updated ego.powerflow to also accept settings from the args-section, that are not yet available as a column in the results_meta. These will be inserted as a list in the column "misc". Changes were commited to the dev branch already and therefore should be included in the PR.

The needed changes in ego.io were commited to a seperate branch, which has now an open PR @ulfmueller. Those weren't major changes so that shouldn't be a problem.
If that PR is merged a new PR dev-->master could be created I guess. I think @nesnoj was already preparing a release (e.g. new version number) ?

**Comment by ulfmueller** [comment]
I merged the ego.io changes into dev.

**Comment by lukasol** [comment]
ego.io has been released with v0.2.11 and
ego.powerflow has been released with v0.0.5

The requirements of eTraGo have been updated accordingly. A new update may be necessary once the pypi release has been carried out.
