### ISSUE TITLE
Update to plot.py 

### ISSUE THREAD

**Issue by Alonsoju95** [openego/eTraGo#532]
Changes in v_nom

**Comment by Alonsoju95** [comment]
Hi @CarlosEpia 
I made some changes in plot.py and now it plots v_nom like this: 
![V-Nom](https://user-images.githubusercontent.com/95680674/206681714-916c4fb6-3c89-4aa1-aa82-dc883ca14301.png)

The name of the branch is feature/#532-update-to-plotpy
Yesterday I pushed the changes to this branch. 
Alonso

**Comment by CarlosEpia** [comment]
It looks nice!
Now you can proceed with the next option: line_colors= "expansion_abs". I would say that you can continue working on the same branch.

**Comment by Alonsoju95** [comment]
Hi Carlos, 
Expansion abs looks like this: 
![image](https://user-images.githubusercontent.com/95680674/207281842-b181d14a-e1e7-4920-9134-d2d3fc86be5d.png)

Should I change something there?

**Comment by CarlosEpia** [comment]
> Hi Carlos, Expansion abs looks like this: ![image](https://user-images.githubusercontent.com/95680674/207281842-b181d14a-e1e7-4920-9134-d2d3fc86be5d.png)
> 
> Should I change something there?

Since plot_grid was created when we had only AC and DC lines, the idea is to check the impact of the other sectors. I would prefer to continue seeing just the electrical network (lines and buses). Please check that it is working like that. Once you are done with that, the idea is to go through all the other options and check/adapt the impact of the additional sectors now included.
