### ISSUE TITLE
Move ego.powerflow functionalties to eTraGo

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#54]
We decided to get rid of the package ego.powerflow and include our functionalities into eTraGo.

**Comment by mariusves** [comment]
First iteration of this issue is commited to the branch  https://github.com/openego/eTraGo/tree/feature/dissolve-ego-powerflow-in-etrago

**Comment by ulfmueller** [comment]
How far is this?
I would like to include it into the upcoming release!

**Comment by mariusves** [comment]
I tested it and could not find any major issues or bugs (since this didn't contain any big changes I guess) . I think it's ready to be merged. Shall I create the PR?

**Comment by mariusves** [comment]
Merge complete.

@MarlonSchlemminger How far are the latest changes to ego.powerflow? Since you made some changes (I think regarding german dispatch etc.), these are not yet included in eTrago. How far is the development of that branch? When finished, please tell me so I can merge the new functionality into eTrago and then we can finally delete ego.powerflow since it's obsolete.

**Comment by MarlonSchlemminger** [comment]
You can merge german-dispatch, I am done with that.

**Comment by mariusves** [comment]
As of now, all functionalities of ego.powerflow have been integrated into eTrago. Therefore, this ticket will be closed.
