### ISSUE TITLE
random noise twice

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#55]
It seems that [this](https://github.com/openego/eTraGo/blob/dev/etrago/appl.py#L74-L77) equals [that](https://github.com/openego/eTraGo/blob/dev/etrago/appl.py#L87-L93). Can we delete the first mentioned lines of code?

**Comment by lukasol** [comment]
Yeah I know it is odd. We could do so, but the idea behind it was to reproduce the noise for the same network set each time. Otherwise, a new noise will be generated each time etrago is run. That's why I wanted to assign the noise before the function, which is now not possible any longer due to the network creation within the function. 
Would you have any idea how we could reproduce the noise more elegantly?

**Comment by ulfmueller** [comment]
wouldnt it be an option, that if you want to use an 'old' / already produced noise that you state that in the args e.g. by stating a path to the noise file? If you do not do that but you do want a noise a new one is created (which you can use for further use if you like).

**Comment by lukasol** [comment]
Good idea, I pushed something like that into dev.
