### ISSUE TITLE
Heatmap to plot v_mag_pu

### ISSUE THREAD

**Issue by MarlonSchlemminger** [openego/eTraGo#60]
The goal is to implement a new function which plots a heatmap showing the voltage at each bus to identify areas with high voltages.

**Comment by MarlonSchlemminger** [comment]
Just a picture we can talk about tomorrow.
![example](https://user-images.githubusercontent.com/22960010/31231599-9ad45a2a-a9e7-11e7-97df-62618b241722.png)

**Comment by ulfmueller** [comment]
Nice. Looks good. I just remembered a [plot for the nodal prices](https://pypsa.org/examples/scigrid-lopf-then-pf.html) (in row [25]) . The problem is basically the same. So you could just use that graphing functionality. Sorry, I just remembered that. But maybe you can take a look at that in order to implement a legend.

**Comment by ulfmueller** [comment]
@MarlonSchlemminger What is the status here?
Have you done a Pull Request to merge it to the dev?

**Comment by MarlonSchlemminger** [comment]
I was not satisfied with my work as I was not able to implement the feature to manually set boundaries as I did for plot_line_loading and then got busy with the renpass stuff and forgot about this one. The status which is currently in the branch works but doesn't have the feature. I would suggest I don't pull yet and try to add manual boundaries first.

**Comment by ulfmueller** [comment]
OK!

**Comment by MarlonSchlemminger** [comment]
Fixed it and merged into dev.
