### ISSUE TITLE
Save results of k-means clustering

### ISSUE THREAD

**Issue by lukasoldi** [openego/eTraGo#62]
See #6 

- [ ]  add functionality to save the resulting cluster for reproducibility

**Comment by wolfbunke** [comment]
I was check the new function of  [results_to_oedb](https://github.com/openego/ego.powerflow/blob/dev/egopowerflow/tools/io.py). At the moment it looks for me that this function is already doing this task or?

I took a look into the result arguments of the clustering ` dir(network) `which I can also find in the **`results_to_oedb `** function. The data set after clustering holds only the cluster results data. For my understanding this saves  the resulting cluster for reproducibility. @lukasoldi @ulfmueller ?

@mariusves could you please check if my assumptions are right by testing?

**Comment by mariusves** [comment]
Unfortunately in it's current state the export function with k_means enabled does not work. I'm going to implement a small fix.

The problem is the results_meta table and the datatype of certain columns e.g. k_means_clustering which was of boolean type before but now is kind of both: boolean or integer.

Maybe I should change the result meta completely, so that it takes all given arguments as a list (sql column type text) and only certain parameters such as the date of the calculation get their own column.

**Comment by ulfmueller** [comment]
Is this solved by now?

**Comment by wolfbunke** [comment]
Since the disaggregation and the csv export are implemented. Do we have a functionality to save the resulting cluster for reproducibility. @ulfmueller @BartelsJ I would like to remove the 0.7 Release tag and place this issue as an nice-to-have issue. What is your opinion on this?

**Comment by ulfmueller** [comment]
well, may be it has to redefined what this issue is about.
We have a 'load_cluster' functionality which enables to reproduce a k-means busmap.
Like you said, we have a csv export (and import).
Where I am not 100% up to date is, whether we can store k-means clustering results in the oedb. If this is not working, we can add it as a nice-to-have (even though it is a bit a pity because I think it is only a matter of ids. They become a string when using k-means clustering. The main problem was already solved by @mariusves )

**Comment by BartelsJ** [comment]
I agree putting this issue as nice-to-have. There is a way to save clustering results in the oedb via load_cluster => save as .csv => export to oedb, so it would be great to have a direct way, but still possible without the results2oedb function.

**Comment by ulfmueller** [comment]
k-means results can now also be loaded into the oedb.
