### ISSUE TITLE
Too few clusters in germany

### ISSUE THREAD

**Issue by MGlauer** [openego/eTraGo#77]
Using k-Means clustering with *NEP 2035* yields 9 Clusters. The reason seems to be that all but 9 weightings are set to 0 - thus only 9 Buses are distributed in 100 Clusters.

Is this linked to the [missing `conv types` in non-SH scenarios](https://github.com/openego/eTraGo/blob/7754b410a8d5401e211a67a6c44c5120ef549674/etrago/cluster/networkclustering.py#L325) or does it point to a deeper bug?

**Comment by ulfmueller** [comment]
That's right. I got the same problem. Good question. I will try out if it has to do with the inflexible weakness you pointed out.
@wolfbunke Can you come up with a more generic solution which also works for other non-SH scenarios such as our 'normal' scenarios?

**Comment by ulfmueller** [comment]
I checked it and the result is as I expected. This problem does not have to do with the conv types. So it seems to be another bug, hopefully not a deeper one. Can anyone look for the reasons? @wolfbunke @BartelsJ ?

**Comment by wolfbunke** [comment]
@BartelsJ  could you take a look to this problem?

**Comment by wolfbunke** [comment]
Thank you @ulfmueller !

**Comment by BartelsJ** [comment]
Sure, I'm on it

**Comment by ulfmueller** [comment]
After @BartelsJ told me that the same problem occurs when applying clustering to the SH scenario I checked my simulations on SH a couple month ago. They were still fine concerning the k. After thinking about what had changed in the meantime I switched back to the old simple weighting using these [lines](https://github.com/openego/eTraGo/blob/dev/etrago/cluster/networkclustering.py#L399-L400) instead of the more sophisticated method being called [here](https://github.com/openego/eTraGo/blob/dev/etrago/cluster/networkclustering.py#L401-L402).
Turns out, then it worked fine again for all scenarios. So the problem lies within the more sophisticated weighting method implemented by @wolfbunke

**Comment by wolfbunke** [comment]
@ulfmueller thanks for checking the methods. I will take a look into it and try to find the buggy part.

**Comment by wolfbunke** [comment]
After checking the kmean in  0cbaa1b by using the `SH Status Quo` data from v02.11 with ` 'start_snapshot': 1`, ` 'end_snapshot' : 24` as well as from time step 2000 to 2020. 
I found the problem by many equal (zero) values in generation and different numbers of load and generator buses. This data set has original 91 buses of which 14 has a p_nom value over zero and 21 load buses with values. 

At the moment I am not sure if I can use an other value instead of p_nom -> p_installed? Or use a random noise as generator p_nom for zero or equal p_nom's?   

I was also using wind and solar which raised the number from 14 to 23 and a k = 20 but still many zero values which is strange or unlucky time steps for a clustering with weighting. Using the` 'load shedding'`results in equal p_nom values which been removed as well.

**Comment by BartelsJ** [comment]
Thank you Wolf for this check. As far as I understand there is one bus representing a certain amount of buses with equal values which leads to a minor number of buses of course. Therefore a random noise vanishes this bug? Did I get that right?
And how did you regard wind and solar in your last statement? Turning out from the second time range 2000 - 2020?

**Comment by wolfbunke** [comment]
Yes and no, there are without clustering 91 buses but only 14/15 has different p_nom generation values and 21 have load values. The rest of it is zero or with 'load shedding' has equal p_nom values. 

By using the list [non_conv_types](https://github.com/openego/eTraGo/commit/0cbaa1b08ffb45ab81ecad8378e1fc6835d282e5#diff-77f0fefb715537b2afa929ec210c2118R331) we define the carriers which should be conventional power plants in the SQ scenario in order to represent / weight the grid see: #6 . I was expecting that by allowing solar and wind as carrier more then 14/23 buses will have unequal p_nom values. But it looks like many buses have zero values.

The second time range was used in order to check if the result were accidentally.

**Comment by ulfmueller** [comment]
sorry, I would like to help but I do not understand you. Maybe we can talk about your findings tomorrow in vivo?!

**Comment by wolfbunke** [comment]
Did you used `network_clustering': True` in your args setting? @BartelsJ  @ulfmueller

**Comment by ulfmueller** [comment]
of course not. why?

**Comment by wolfbunke** [comment]
The problem caused be the weighting factor which is fix in #93 now. An more generic solution is needed.

**Comment by BartelsJ** [comment]
This is fixed by Wolfs work and a bus_weighting .csv-file, isn't it?

**Comment by wolfbunke** [comment]
I think so. @ulfmueller  do you have any open tasks for this ticket?
