### ISSUE TITLE
create interface between etrago results and etrago

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#91]
once having stored results in the oedb it would be helpful to be able to import this data again into an pypsa network. 
The work @maltesc did for eDisGo might be useful for this?!
@mariusves What do you think?

**Comment by maltesc** [comment]
@ulfmueller, the basic functionality is identical: the code reads data from the database into a python/pandas data structure.

Whereas the syntax of the specs code ([specs.py](https://github.com/openego/eGo/blob/features/specs/ego/tools/specs.py)) might serve as an example, the explicitly queried data is completely different.

**Comment by ulfmueller** [comment]
@mariusves Have you started this?
@maltesc is also interested in this functionality :wink:

**Comment by mariusves** [comment]
Working on it but no ETA yet ;-)

**Comment by ulfmueller** [comment]
@mariusves was not able to implmement this function. We need someone else who can take over this job. Anyone interested?

**Comment by ulfmueller** [comment]
@wolfbunke you wrote this functionality for eGo, right? It would be nice to use this function also in eTraGo. How should we do this the best way? I guess the best would be to import that function from eGo. Can you prepare this in a branch?

**Comment by wolfbunke** [comment]
yes and there is also a issue in  #128 I add it to milestone 0.7 because of time. The Function can be found here: https://github.com/openego/eGo/blob/dev/ego/tools/io.py#L119-L367. I think the best way is to use it in a new class like [ScenarioBase](https://github.com/openego/eTraGo/blob/dev/etrago/tools/io.py#L45)  and [NetworkScenario](https://github.com/openego/eTraGo/blob/dev/etrago/tools/io.py#L89).

**Comment by wolfbunke** [comment]
I can prepare it for the next release.

**Comment by ulfmueller** [comment]
I guess one issue for this is enough. I suggest to close this one and follow up with the development in #128
